In [1]:
import numpy as np

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
l = range(10000)
%timeit [i**2 for i in l]

5.54 ms ± 108 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
a = np.arange(10000)
%timeit a**2

17.9 µs ± 200 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
a.ndim()

TypeError: 'int' object is not callable

In [11]:
p = np.array([1,2,3,4])
p

array([1, 2, 3, 4])

In [12]:
p.ndim


1

In [13]:
p.shape

(4,)

In [14]:
len(p)

4

In [16]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b.ndim

2

In [18]:
b.shape

(2, 3)

In [19]:
len(b)

2

In [22]:
c = np.array([[[1,2],[3,4],[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [23]:
c.ndim

3

In [24]:
c.shape

(1, 4, 2)

In [25]:
x = np.arange(1,10,2)
x

array([1, 3, 5, 7, 9])

In [29]:
x = np.linspace(0,1,6)   #no. of points
x

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [28]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [34]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [36]:
np.diag(a)

array([1, 2, 3, 4])

In [39]:
a = np.random.rand(4)
a

array([0.00423464, 0.39733081, 0.4056551 , 0.55041143])

In [40]:
a = np.random.randint(4)
a

1

In [41]:
a = np.random.randn(4)
a

array([ 1.70160648,  1.43012253,  0.62639792, -0.15897288])

In [42]:
a = np.arange(10)
a.dtype

dtype('int32')

In [43]:
a = np.arange(10, dtype = float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
a = np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [46]:
a[2][2]

3

In [47]:
a[2][1] = 6
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 6, 3]])